### ISSUE TITLE
Questions about `GetOrder` parsing

### ISSUE THREAD

**Issue by rynkjm** [hakanensari/mws-orders#7]
Hi!

Why does `GetOrder` parse return the first element?

https://github.com/hakanensari/mws-orders/blob/v0.5.1/lib/mws/orders/parser.rb#L36

I was expecting the next behavior.

```ruby
response = client.get_order("XXX-XXXXXXX-XXXXXXX","XXX-XXXXXXX-YYYYYYY")
response.parse
#=> <MWS::Orders::Orders [#<MWS::Orders::Order XXX-XXXXXXX-XXXXXXX>, #<MWS::Orders::Order XXX-XXXXXXX-YYYYYYY>]>
```

But only the first element.

**Comment by hakanensari** [comment]
@rynkjm You're right, I'll fix this

**Comment by rynkjm** [comment]
@hakanensari thank you 👍
